export const DELETE_EVENT = 'DELETE_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';
export const DERETE_ALL_EVENTS = 'DERETE_ALL_EVENTS';

export const ADD_OPERATION_LOG = 'ADD_OPERATION_LOG';
export const DELETE_ALL_OPERATION_LOGS = 'DELETE_ALL_OPERATION_LOGS';
